services:

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Web Console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: payments
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_TRASACTIONS_QUEUE: transaction_queue
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_DATABASE: payments

  worker:
    build: ./worker
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq
      - mysql
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_DATABASE: payments
      WORKER_ID: ${COMPOSE_PROJECT_NAME}-worker-
      START_DELAY: 10

volumes:
  mysql_data: